Swerdle 4 remove roman numbers from the daily rotation
ankarhem/swerdle pull request #5
Opened 2022-08-27 14:04 UTC by JHilmarch

* Excluded roman numbers from the game
* Updated the help page
* Updating readme & added a contributing markdown file

2022-08-29 07:04 UTC, ankarhem requested changes

2022-08-29 07:04 UTC, ankarhem commented on migrations/004-unapprove-roman-numbers.sql
> +UPDATE tbl_words SET approved = 1 WHERE word LIKE '%ii%';
👍🏼

2022-08-29 07:04 UTC, ankarhem commented on src/routes/hjalp.svelte
> +		</li>
Behöver inte ha med detta, man kan anta att romerska siffror inte skall vara med

2022-09-14 21:43 UTC, JHilmarch commented on src/routes/hjalp.svelte
> +		</li>
Ja, jag tog en 'revert' på den commiten nu.

2022-09-16 05:14 UTC, ankarhem approved these changes

2022-09-16 05:14 UTC, merged